package net.zaf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataShip<M extends BaseDataShip<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setNo(java.lang.String no) {
		set("no", no);
	}

	public java.lang.String getNo() {
		return get("no");
	}

	public void setStar(java.lang.String star) {
		set("star", star);
	}

	public java.lang.String getStar() {
		return get("star");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setRarity(java.lang.String rarity) {
		set("rarity", rarity);
	}

	public java.lang.String getRarity() {
		return get("rarity");
	}

	public void setGroup(java.lang.String group) {
		set("group", group);
	}

	public java.lang.String getGroup() {
		return get("group");
	}

	public void setBuildingTime(java.lang.String buildingTime) {
		set("building_time", buildingTime);
	}

	public java.lang.String getBuildingTime() {
		return get("building_time");
	}

}
