package net.zaf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataShipAdvanced<M extends BaseDataShipAdvanced<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setShipId(java.lang.String shipId) {
		set("ship_id", shipId);
	}

	public java.lang.String getShipId() {
		return get("ship_id");
	}

	public void setAdvName(java.lang.String advName) {
		set("adv_name", advName);
	}

	public java.lang.String getAdvName() {
		return get("adv_name");
	}

	public void setAdvContent(java.lang.String advContent) {
		set("adv_content", advContent);
	}

	public java.lang.String getAdvContent() {
		return get("adv_content");
	}

}
