package net.zaf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysFun<M extends BaseSysFun<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setDisplay(java.lang.String display) {
		set("display", display);
	}

	public java.lang.String getDisplay() {
		return get("display");
	}

	public void setCtl(java.lang.String ctl) {
		set("ctl", ctl);
	}

	public java.lang.String getCtl() {
		return get("ctl");
	}

	public void setAct(java.lang.String act) {
		set("act", act);
	}

	public java.lang.String getAct() {
		return get("act");
	}

	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}

	public java.lang.Integer getLevel() {
		return get("level");
	}

	public void setIsEnabled(java.lang.String isEnabled) {
		set("is_enabled", isEnabled);
	}

	public java.lang.String getIsEnabled() {
		return get("is_enabled");
	}

	public void setNo(java.lang.String no) {
		set("no", no);
	}

	public java.lang.String getNo() {
		return get("no");
	}

}
