package net.zaf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataGate<M extends BaseDataGate<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setNeedLevel(java.lang.String needLevel) {
		set("need_level", needLevel);
	}

	public java.lang.String getNeedLevel() {
		return get("need_level");
	}

	public void setBossAdd(java.lang.String bossAdd) {
		set("boss_add", bossAdd);
	}

	public java.lang.String getBossAdd() {
		return get("boss_add");
	}

	public void setClearAward(java.lang.String clearAward) {
		set("clear_award", clearAward);
	}

	public java.lang.String getClearAward() {
		return get("clear_award");
	}

	public void setAwardList(java.lang.String awardList) {
		set("award_list", awardList);
	}

	public java.lang.String getAwardList() {
		return get("award_list");
	}

}
