package net.zaf.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDataShipSkill<M extends BaseDataShipSkill<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setShipId(java.lang.String shipId) {
		set("ship_id", shipId);
	}

	public java.lang.String getShipId() {
		return get("ship_id");
	}

	public void setSkillName(java.lang.String skillName) {
		set("skill_name", skillName);
	}

	public java.lang.String getSkillName() {
		return get("skill_name");
	}

	public void setSkillContent(java.lang.String skillContent) {
		set("skill_content", skillContent);
	}

	public java.lang.String getSkillContent() {
		return get("skill_content");
	}

}
