package net.zaf.model;

import net.zaf.model.base.BaseDataShip;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataShip extends BaseDataShip<DataShip> {
	public static final DataShip dao = new DataShip().dao();
}
