package net.zaf.model;

import net.zaf.model.base.BaseDataShipPerformance;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataShipPerformance extends BaseDataShipPerformance<DataShipPerformance> {
	public static final DataShipPerformance dao = new DataShipPerformance().dao();
}
