package net.zaf.model;

import net.zaf.model.base.BaseDataShipPerformanceEvaluate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataShipPerformanceEvaluate extends BaseDataShipPerformanceEvaluate<DataShipPerformanceEvaluate> {
	public static final DataShipPerformanceEvaluate dao = new DataShipPerformanceEvaluate().dao();
}
