package net.zaf.model;

import net.zaf.model.base.BaseDataIndex;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataIndex extends BaseDataIndex<DataIndex> {
	public static final DataIndex dao = new DataIndex().dao();
}
