package net.zaf.model;

import net.zaf.model.base.BaseDataGate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataGate extends BaseDataGate<DataGate> {
	public static final DataGate dao = new DataGate().dao();
}
