package net.zaf.model;

import net.zaf.model.base.BaseDataShipAdvanced;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataShipAdvanced extends BaseDataShipAdvanced<DataShipAdvanced> {
	public static final DataShipAdvanced dao = new DataShipAdvanced().dao();
}
