package net.zaf.model;

import net.zaf.model.base.BaseDataShipSkill;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataShipSkill extends BaseDataShipSkill<DataShipSkill> {
	public static final DataShipSkill dao = new DataShipSkill().dao();
}
