package net.zaf.model;

import net.zaf.model.base.BaseDataShipPerformanceMax;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataShipPerformanceMax extends BaseDataShipPerformanceMax<DataShipPerformanceMax> {
	public static final DataShipPerformanceMax dao = new DataShipPerformanceMax().dao();
}
