package net.zaf.model;

import net.zaf.model.base.BaseSysFun;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysFun extends BaseSysFun<SysFun> {
	public static final SysFun dao = new SysFun().dao();
}
