package net.zaf.model;

import net.zaf.model.base.BaseSysPermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysPermission extends BaseSysPermission<SysPermission> {
	public static final SysPermission dao = new SysPermission().dao();
}
